### PR TITLE
Relax signedness specification in `Object`

### PR DESCRIPTION
**Pull request by mernst**
Merge together:
https://github.com/typetools/checker-framework/pull/5848
https://github.com/typetools/jdk/pull/173
https://github.com/codespecs/daikon/pull/474
https://github.com/plume-lib/multi-version-control/pull/221
https://github.com/plume-lib/plume-util/pull/295

### CODE REVIEW

**Comment by mernst** [comment]
@jpeterson2 Do these changes look right to you?

**Comment by jpeterson2** [comment]
Looking at the referenced commits, it seems correct to me

**Comment by mernst** [comment]
@jpeterson2 I was only asking about the two annotations I added to the JDK.  The other pull requests are *consistent* with this one, but is this one *right*?
Thanks.

**Comment by jpeterson2** [comment]
Yes. There's no situation where instances of an Object that are interpreted as unsigned should have implementations of these methods that differ from the signed default. Therefore, relaxing this constraint is correct.

**Comment by mernst** [comment]
Great.  That was my judgment, but I wanted your confirmation.

**Review by smillst — APPROVED** [review]

**Pull request merged**
