### PR TITLE
Comments and `@AnnotatedFor` from index-java-files

### PR DESCRIPTION
**Pull request by the1derer**
~Don't merge before merging #19 and #59.~

### CODE REVIEW

**Comment by the1derer** [comment]
These are missing:
`java.nio.ByteBuffer`
`java.nio.CharBuffer`

**Comment by mernst** [comment]
> **These are missing in JDK-11:**
> 
> `java.nio.ByteBuffer`
> `java.nio.CharBuffer`
> 
> @mernst Many of the following classes of `sun.misc` are still preset but but their package has been changed so AFU should and haven't inserted the annnotation what should I do?
> 
> `sun.util.LocaleDataMetaInfo`
> `sun.util.LocaleServiceProviderPool`
> `sun.util.TimeZoneNameUtility`
> `sun.misc.FloatingDecimal`
> `sun.misc.FormattingFloatingDecimal`
> `sun.misc.JavaLangAccess`
> `sunmisc.JavaUtilZipAccess`

I don't understand your question.  There is a verb missing after "should" and a noun missing before "haven't".  Can you rewrite it, breaking it into multiple sentences for clarity?

**Comment by the1derer** [comment]
> I don't understand your question. There is a verb missing after "should" and a noun missing before "haven't". Can you rewrite it, breaking it into multiple sentences for clarity?

Done

**Comment by mernst** [comment]
> These are missing in JDK-11:

In that case, we can ignore them.  There is no work to do.

> Many of the following classes of `sun.misc`package are still preset but their package has been changed. ...  Should I manually add annotation?

Yes, please manually transfer the annotations.  We don't wish to lose the annotations.

**Comment by the1derer** [comment]
@mernst Ready to be merged.

> > Many of the following classes of sun.miscpackage are still preset but their package has been changed. ... Should I manually add annotation?
>
> Yes, please manually transfer the annotations. We don't wish to lose the annotations.

As it turns out all these classes of `sun.misc` package didn't contain any annotations and also they have been changed quite a lot in JDK-11 internally. So, I am not adding `@AnnotatedFor` annotation as I think they should be reannotated according to new documentation.

Thanks.

**Comment by the1derer** [comment]
> There are no comments in this pull request -- just @AnnotatedFor.
> Is that correct?

Yes, it doesn't contain any annotation. Only comments I found in index-jdk was in `java.nio.CharBuffer` which doesn't exist in JDK-11

**Pull request merged**
