### PR TITLE
All stubs merged

### PR DESCRIPTION
**Pull request by the1derer**
All annotations from stub files.
Don't merge before merging #17 and #18

### CODE REVIEW

**Comment by the1derer** [comment]
Before merging please merge my braches of  #14, #7 to `all-stubs-merged` branch.

**Comment by mernst** [comment]
@the1derer You assigned this to me, but it is still a draft pull request.

**Comment by mernst** [comment]
> Before merging please merge my braches of #14, #7 to `all-stubs-merged` branch. I have made some changes.

You can create pull requests for those changes, and only assign this to me after those pull requests are merged.

**Comment by mernst** [comment]
Why is this pull request into master rather than into `jdk-from-stubfiles`?  I would have expected it to be into `jdk-from-stubfiles`, per the organization of the branches.  Branch `all-stubs-merged` was just temporary, to resolve merge conflicts.

**Comment by the1derer** [comment]
@mernst  Sorry I got confused. I have changed the base.

**Pull request merged**
