### PR TITLE
Allow nulls for Method.invoke(null) and Field.get(null)

### PR DESCRIPTION
**Pull request by vlsi**
The nulls are permitted there to access static fields and methods

### CODE REVIEW

**Comment by vlsi** [comment]
test_plume_lib build fails because it has `@SuppressWarnings(nullness:argument.type.incompatible)` to suppress `field.get(null)`:  https://github.com/plume-lib/options/blob/24be095f55cd9f521b25f5409738e48dd4370481/src/main/java/org/plumelib/options/Options.java#L425

So plume_lib should be adjusted (excessive suppression should be removed) after this PR is merged.

**Comment by cpovirk** [comment]
This is requested occasionally, as in https://github.com/typetools/checker-framework/pull/1534. The Checker Framework policy is to declare the parameters as non-null to avoid any chance of `NullPointerException`. There was a comment about this [in the old nullness stub](https://github.com/typetools/checker-framework/blob/checker-framework-3.3.0/checker/jdk/nullness/src/java/lang/reflect/Method.java#L109). Perhaps it should be carried over to the new file that you're editing here. Additionally, you could consider a PR to provide a separate astub file, as proposed in https://github.com/typetools/checker-framework/issues/3258

**Comment by vlsi** [comment]
@cpovirk , thanks for looking into this, however, it looks like you are confused.

The PR allows `null` inputs for `instance` parameter.
Currently, checkerframework forbids to call static methods via reflection, and it does not really help to track nullability issues :(

That is why I believe it should be generally possible to call `field.get(null)` to get the value of a static field.

Of course, I can add a stub to my project, however, it is sad that the default mode is "you can't use reflection" :-/

**Comment by vlsi** [comment]
The comment you mention says "warning", however, in practice the code like `field.get(null)` raises an error rather than a warning.

**Comment by vlsi** [comment]
Ah, you want to have non-standard stub. Ok, then I would put that stub into pgjdbc for a while.

**Pull request closed without merging**
