### PR TITLE
Add `@Covariant` to some `java.util.function` types.

### PR DESCRIPTION
**Pull request by cpovirk**
See https://github.com/typetools/checker-framework/issues/1444

### CODE REVIEW

**Comment by cpovirk** [comment]
Hmm, not sure exactly what's wrong here:

```
tests.ValueNonNullStringsConcatenationTest > run[value-non-null-strings-concatenation] FAILED
    java.lang.AssertionError: 20 out of 20 expected diagnostics were found.
    2 unexpected diagnostics were found:
    Binaries.java:259: error: (assignment.type.incompatible)
    Binaries.java:261: error: (assignment.type.incompatible)
    While type-checking /__w/1/checker-framework/framework/tests/value-non-null-strings-concatenation/Binaries.java, ...
```

Here are [line 259](https://github.com/typetools/checker-framework/blob/6db45f4cb400ba3194c0f31ed5a75d2baf69e690/framework/tests/value-non-null-strings-concatenation/Binaries.java#L259) and [line 261](https://github.com/typetools/checker-framework/blob/6db45f4cb400ba3194c0f31ed5a75d2baf69e690/framework/tests/value-non-null-strings-concatenation/Binaries.java#L261).

```
daikon/split/FileCompiler.java:101: error: [value:argument.type.incompatible] incompatible types in argument.
    this(compiler.trim().split(" +"), timeLimit);
                              ^
  found   : @UnknownVal String @UnknownVal []
  required: @UnknownVal String @ArrayLenRange(from=1, to=2147483647) []
```

```
/tmp/multi-version-control/src/main/java/org/plumelib/multiversioncontrol/MultiVersionControl.java:805: error: [lowerbound:array.access.unsafe.low] Potentially unsafe array access: the index could be negative.
            String possibleRoot = rootWords[rootWords.length - 1];
                                                             ^
  found   : @GTENegativeOne int
  required: an integer >= 0 (@NonNegative or @Positive)
/tmp/multi-version-control/src/main/java/org/plumelib/multiversioncontrol/MultiVersionControl.java:839: error: [lowerbound:argument.type.incompatible] incompatible types in argument.
        root = root.substring(0, root.length() - 1);
                                               ^
  found   : @GTENegativeOne int
  required: @NonNegative int
/tmp/multi-version-control/src/main/java/org/plumelib/multiversioncontrol/MultiVersionControl.java:1094: error: [lowerbound:argument.type.incompatible] incompatible types in argument.
          repository = repository.substring(0, repository.length() - 1);
                                                                   ^
  found   : @GTENegativeOne int
  required: @NonNegative int
```

**Comment by mernst** [comment]
Thanks for these improvements, and sorry for not noticing them (my notifications for this repository got turned off).

This pull request requires a change to test `Issue1633.java` (to remove a false positive warning).
I can't make that change in your fork, so I will make a new pull request.

**Comment by mernst** [comment]
The CI job passed, but that is due to a bug in Azure Pipelines.  (It sometimes reports old successful jobs when asked to run a new job.)

A change in `Issue1633.java` was needed, and I made it in a separate pull request.  Thanks again for the improvements.

**Comment by cpovirk** [comment]
Thanks for figuring out what was wrong for me.

(I figured there might be a notification issue :))

**Comment by cpovirk** [comment]
> I can't make that change in your fork, so I will make a new pull request.

Huh, I see now that "Allow edits by maintainers" defaults to on for my new PRs, so either the default changed, or I mis-clicked. Thanks for letting me know so that I could check.

**Pull request closed without merging**
