### PR TITLE
Add nullness annotations to Logger.java

### PR DESCRIPTION
**Pull request by the1derer**
Manually Transferred Annotation.

Don't merge yet. Oracle has changed this class drastically and since many projects will depend on this class, I will manually annotate it fully.

### CODE REVIEW

**Comment by mernst** [comment]
@the1derer The description says "Don't merge yet."
Is this ready for review and merging?

**Comment by the1derer** [comment]
> @the1derer The description says "Don't merge yet."
> Is this ready for review and merging?

@mernst I am planning to add nullness annotation using Checker-Framework 3.0 when we have fully integrated Annotated-JDK 11. This is a non-critical PR so I will add annotations after all the other work is done.

**Comment by mernst** [comment]
Why is this PR non-critical?
If possible, I would like to ship a complete JDK when Checker Framework 3.0.0 is released.

**Comment by the1derer** [comment]
@mernst 
Please revert changes of this PR. There is something wrong that I don't understand for now and is causing errors in build.
Thanks.

**Comment by mernst** [comment]
I am willing to do so, but I don't understand why reverting is sufficient or necessary.

Is reverting this pull request sufficient?  If you don't understand the problem, how do you know that this particular pull request is the culprit, and reverting it will fix the problem?

Is reverting this pull request necessary?  If you want to obtain a version of the code that predates this pull request being merged, you can obtain it from the git version history.

**Comment by the1derer** [comment]
@mernst 
Because of this PR `annotation-from-java-files` branch [doesn't compile](https://dev.azure.com/typetools/jdk/_build/results?buildId=435&view=logs&jobId=9a7c86c9-73e3-5d16-bfb4-c8c570f01ef7&taskId=1a3dbb97-47a8-55a0-2445-da665897a54d&lineStart=672&lineEnd=673&colStart=1&colEnd=1) and reverting the change because of this PR i.e commit 535b3539873630f40b7dbb0c777987e247453f36 makes compilation successful.

**Pull request merged**
