### PR TITLE
Annotations from Java files - 07/27/2019

### PR DESCRIPTION
**Pull request by the1derer**
This PR contains all the annotations from (annotated)jdk8.jar and is transferred using a script.

~Don't review till annotations from typetools/checker-framework#2523 are also added.~

**After merging this PR also merge following PRs:**
#12 #13

### CODE REVIEW

**Comment by the1derer** [comment]
@mernst Annotations from Signedness-JDK added.
I will create a separate PR to my own branch to change annotations mentioned in `TODO` from Signedness-JDK.

**Comment by the1derer** [comment]
@mernst Ready for review.

**Comment by mernst** [comment]
> This pull request has to be merged at very last.

Is this still necessary?  There are other pull requests open in this repository, but I think I should be able to merge this pull request.

**Comment by the1derer** [comment]
> Is this still necessary? There are other pull requests open in this repository, but I think I should be able to merge this pull request.
@mernst  Ready to be merged.No need to wait now.

**Pull request merged**
