### PR TITLE
Annotate Proxy and ExecutionException for nullness.

### PR DESCRIPTION
**Pull request by cpovirk**
Also, mark Iterator, which was already annotated, with
@AnnotatedFor("nullness").

### CODE REVIEW

**Comment by mernst** [comment]
Thanks, Chris!

**Comment by cpovirk** [comment]
Thanks for handling the private methods.

I have a couple more of these in flight. Would you like me to annotate the private methods in those? I see that 31.1.4 suggests as much, though 31.1.5 then leaves open the possibility of not doing so.

**Comment by mernst** [comment]
Please go ahead and submit the pull requests, with or without the private methods.  (In case it matters, there will be a release on Monday.)

Here are some reasons to annotate private methods:
 * aesthetics:  it's nice to have the job complete
 * type-checking the JDK:  when we get around to type-checking the JDK, having the private methods annotated will make doing so easier.  But, we are not doing that yet.
 * it's not that much extra work to do it, once you are already reading all the code

The annotated JDK is just as useful for type-checking, with or without the private annotations.

**Comment by cpovirk** [comment]
Neat to hear that type-checking the JDK is something that may start happening someday. Thanks for the info. I will try to exercise some judgment in what I do.

**Pull request merged**
