### PR TITLE
Annotate Scanner, MessageDigest, MessageDigestSpi, and System classes, write() of java.io package and toCharArray() of String.java using Signedness Checker

### PR DESCRIPTION
**Pull request by gokaco**

### CODE REVIEW

**Comment by gokaco** [comment]
@mernst I am not getting why the tests are failing. Please check.

**Comment by mernst** [comment]
Other than the failing tests, is this pull request complete?  I haven't heard from you about it.

**Comment by gokaco** [comment]
> Other than the failing tests, is this pull request complete? I haven't heard from you about it.
@mernst 
Was about to tell you. Yes it is complete.

**Comment by mernst** [comment]
The build is failing for the same reason as https://github.com/typetools/jdk/pull/19,
so this cannot be merged until @the1derer fixes that pull request.

**Comment by the1derer** [comment]
@mernst @gokaco Errors in this PR are not due to #19 instead @gokaco  should pull `typetools/jdk:master` to your branch.

**Comment by mernst** [comment]
To resolve the CI failure, please follow the instructions at 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README" (and ask a question or make a suggestion if they are unclear or they do not work).

**Comment by mernst** [comment]
@gokaco Have you abandoned this pull request?

**Comment by gokaco** [comment]
> @gokaco Have you abandoned this pull request?

@mernst  Working on it using the link you have given above. WIll give you the update.

**Comment by gokaco** [comment]
@mernst
```
Reference JAR:/__w/1/jdk11u/build/linux-x86_64-normal-server-release/test-support/jtreg_test_jdk_tier1/scratch/java-rt.jar
Compared  JAR:/__w/1/jdk11u/build/linux-x86_64-normal-server-release/test-support/jtreg_test_jdk_tier1/scratch/native-rt.jar
FAIL
STDERR:
java.lang.RuntimeException: java.lang.RuntimeException: process failed with non-zero exit
	at Pack200Test.doPackUnpack(Pack200Test.java:121)
	at Pack200Test.main(Pack200Test.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:574)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: process failed with non-zero exit
	at Utils.runExec(Utils.java:540)
	at Utils.runExec(Utils.java:500)
	at Utils.runExec(Utils.java:496)
	at Utils.doCompareBitWise(Utils.java:174)
	at Pack200Test.doPackUnpack(Pack200Test.java:118)
	... 7 more
```

**Comment by mernst** [comment]
No changes against upstream.

**Pull request closed without merging**
