### PR TITLE
Annotations and Comments from interning/jdk.astub

### PR DESCRIPTION
**Pull request by the1derer**
Annotations and Comments from [interning/jdk.astub](https://github.com/typetools/checker-framework/blob/9d0ac6c64d01b5d31e83e9a34be09e4e4de8ad8e/checker/src/main/java/org/checkerframework/checker/guieffect/jdk.astub#L11)

### CODE REVIEW

**Comment by the1derer** [comment]
[java.util.XMLUtils](https://github.com/typetools/checker-framework/blob/9d0ac6c64d01b5d31e83e9a34be09e4e4de8ad8e/checker/src/main/java/org/checkerframework/checker/interning/jdk.astub#L100) is not present in JDK11

**Comment by mernst** [comment]
This pull request is marked as a draft.  What is its status?

**Comment by the1derer** [comment]
@mernst Sorry for the delay. I thought that I have small work to do but it turns out there are approximately 300 classes more to which I have to only add `@UsesObjectEquals`. I am adding them right now. But it could take some time.

**Comment by mernst** [comment]
OK.  I just resolved the merge conflicts against upstream, so you should pull soon to avoid more merge conflicts.

**Comment by the1derer** [comment]
@mernst Ready for review.
Where should I place [this comment](https://github.com/typetools/checker-framework/blob/9d0ac6c64d01b5d31e83e9a34be09e4e4de8ad8e/checker/src/main/java/org/checkerframework/checker/interning/jdk.astub#L3)?

**Comment by mernst** [comment]
> @mernst Ready for review.
> Where should I place [this comment](https://github.com/typetools/checker-framework/blob/9d0ac6c64d01b5d31e83e9a34be09e4e4de8ad8e/checker/src/main/java/org/checkerframework/checker/interning/jdk.astub#L3)?

I don't think that comment is relevant any more; you can leave it out.

**Comment by the1derer** [comment]
> I don't think that comment is relevant any more; you can leave it out.

OK, then ready to merged.

**Pull request merged**
