### PR TITLE
Non-Empty Checker

### PR DESCRIPTION
**Pull request by mernst**
Merge together with:
 * https://github.com/typetools/checker-framework/pull/6658
 * https://github.com/typetools/jdk17u/pull/8
 * https://github.com/plume-lib/plume-util/pull/403

### CODE REVIEW

**Review by smillst — APPROVED** [review]

**Comment by smillst** [comment]
@mernst I'm not sure why the tests aren't passing.

**Comment by jyoo980** [comment]
@smillst @mernst If the tests continue to fail, I'm happy to open smaller PRs that incorporates the Non-Empty annotations, gradually.

**Comment by smillst** [comment]
> @smillst @mernst If the tests continue to fail, I'm happy to open smaller PRs that incorporates the Non-Empty annotations, gradually.

The problem is that nonempty.qual package isn't found:
```
/__w/1/s/src/java.base/share/classes/java/nio/charset/Charset.java:28: error: package org.checkerframework.checker.nonempty.qual does not exist
import org.checkerframework.checker.nonempty.qual.EnsuresNonEmptyIf;
```
So, fewer annotations won't help.

**Comment by mernst** [comment]
@jyoo980 I will look into this.

**Pull request closed without merging**
