### PR TITLE
`@AnnotatedFor` from signedness java files

### PR DESCRIPTION
**Pull request by the1derer**

### CODE REVIEW

**Comment by the1derer** [comment]
These Classes are not in JDK-11:

`com.sun.cobra.se.impl` package

**Comment by the1derer** [comment]
@mernst 
Ready to be merged.

**Comment by the1derer** [comment]
@mernst 
I have made the whitespace changes consistent and now ready to be merged.

Thanks.

**Comment by mernst** [comment]
@the1derer The point is not to make the whitespace consistent across the project.  Rather, the point is to reduce the size of the diffs against upstream.  Thus, the whitespace should be consistent with what it was upstream.

**Pull request merged**
