### PR TITLE
Annotate parameters of java.lang.AssertionError(String, Throwable) co…

### PR DESCRIPTION
**Pull request by eaftan**
…nstructor

The Javadoc for the constructor says both parameters may be null.

### CODE REVIEW

**Comment by wmdietl** [comment]
Thanks for the PR and sorry that nobody noticed it for so long.
I opened a corresponding CF PR: https://github.com/typetools/checker-framework/pull/3159

**Comment by eaftan** [comment]
No worries, thanks @wmdietl!  For my information, what is the difference between this annotated JDK and the one in typetools/checker-framework?

**Comment by wmdietl** [comment]
> No worries, thanks @wmdietl! For my information, what is the difference between this annotated JDK and the one in typetools/checker-framework?

This repository contains annotations for multiple type systems, is parsed as stub files at runtime, and is used on Java 9+ JVMs.

The one in typetools/checker-framework is split-up by type system, is compiled into the annotated JDK `jdk8.jar` file, and is used on the Java 8 compilation bootclasspath.
We're working on deprecating that version and only using typetools/jdk.

Also see https://github.com/typetools/checker-framework/blob/master/checker/jdk/README

**Comment by wmdietl** [comment]
Thanks again. You can delete your branch now, if you want.

**Pull request merged**
