### PR TITLE
Add script to create JAR files

### PR DESCRIPTION
**Pull request by the1derer**

### CODE REVIEW

**Comment by mernst** [comment]
Before marking this pull request as ready for review, please add documentation, make it download any files that are needed, etc.  That is, please make it complete.  Thanks!

**Comment by the1derer** [comment]
@mernst Should I move this PR to `typetools/jdk11u` since we are going to ship compiled version of `jdk11u` instead of `jdk`

**Comment by mernst** [comment]
> Should I move this PR to `typetools/jdk11u` since we are going to ship compiled version of `jdk11u` instead of `jdk`?

No.  Its README says [](https://github.com/typetools/jdk11u/blob/master/README#L7) says "Do not edit this repository."  We will need the same logic for jdk12u, jdk13u, etc., so it should not be added to just one of them.

**Comment by mernst** [comment]
I'm merging this so the work is not lost, but this is not finished because it lacks documentation -- none within the code, and none about how to use it.

**Pull request merged**
