### PR TITLE
Add annotation to ResourceBundle.java

### PR DESCRIPTION
**Pull request by the1derer**
These annotations are transferred manually.

### CODE REVIEW

**Comment by the1derer** [comment]
> This looks reasonable, but why is there a pull request for these few annotations, separately from the rest of the lock annotations?

AFU was not able to transfer these annotations so I have to move these annotations manually. I figured it would be better to create a separate PR for work done manually.

**Comment by mernst** [comment]
OK, thanks for the clarification.

**Comment by mernst** [comment]
@the1derer Did you submit a bug report for AFU's inability to insert these annotations?

**Comment by the1derer** [comment]
@mernst I have submitted a bug typetools/annotation-tools#232

**Pull request merged**
